version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    ports:
      - "27017:27017"
    networks:
      - react

  backend:
    build:
      context: ./Techdome-backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - MONGO_URI=mongodb://root:12345678@mongodb:27017/mydatabase
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - react

  frontend:
    build:
      context: ./Techdome-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL=http://backend:5000/api
    depends_on:
      - backend
    networks:
      - react

networks:
  react:
    driver: bridge

